services:
  - type: web
    name: ratekth
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ratekth_db
          property: connectionString
      - key: FLASK_EMAIL_USER
        sync: false
      - key: FLASK_EMAIL_PASS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: ratekth_db
    plan: free

